version: '3.8'

services:
  postgres_keycloak:
    image: postgres
    container_name: keycloak-postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    restart: unless-stopped
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data

  postgres_hapi:
    image: postgres
    container_name: hapi-postgres
    environment:
      POSTGRES_DB: hapi
      POSTGRES_USER: hapi
      POSTGRES_PASSWORD: hapi
    restart: unless-stopped
    volumes:
      - hapi_postgres_data:/var/lib/postgresql/data

  keycloak:
    image: jboss/keycloak:latest
    container_name: keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres_keycloak
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
    ports:
      - "8081:8080"
      - "8443:8443"
    restart: unless-stopped
    depends_on:
      - postgres_keycloak

  hapi_fhir:
    image: hapiproject/hapi:latest
    container_name: hapi-fhir
    ports:
      - "8080:8080"
    environment:
      - HAPI_FHIR_SERVER_DATABASE_DRIVER=org.postgresql.Driver
      - HAPI_FHIR_SERVER_DATABASE_URL=jdbc:postgresql://postgres:5432/hapi
      - HAPI_FHIR_SERVER_DATABASE_USERNAME=hapi
      - HAPI_FHIR_SERVER_DATABASE_PASSWORD=hapi
    restart: unless-stopped
    depends_on:
      - postgres_hapi
    volumes:
      - ./hapi-fhir.properties:/usr/local/tomcat/conf/hapi-fhir.properties

volumes:
  keycloak_postgres_data:
  hapi_postgres_data:
